Failure # 1 (occurred at 2024-09-01_21-59-51)
[36mray::IMPALA.train()[39m (pid=2666410, ip=143.248.233.21, actor_id=c2e85f56daa9972de977e2d901000000, repr=IMPALA)
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 328, in train
    result = self.step()
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 951, in step
    train_results, train_iter_ctx = self._run_one_training_iteration()
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 3600, in _run_one_training_iteration
    training_step_results = self.training_step()
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/algorithms/impala/impala.py", line 653, in training_step
    return self._training_step_old_api_stack()
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/algorithms/impala/impala.py", line 1030, in _training_step_old_api_stack
    self._get_samples_from_workers_old_and_hybrid_api_stack(
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/algorithms/impala/impala.py", line 1114, in _get_samples_from_workers_old_and_hybrid_api_stack
    ] = self.env_runner_group.fetch_ready_async_reqs(
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/env/env_runner_group.py", line 1044, in fetch_ready_async_reqs
    _handle_remote_call_result_errors(
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/env/env_runner_group.py", line 1254, in _handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(FileNotFoundError): [36mray::RolloutWorker.apply()[39m (pid=2666544, ip=143.248.233.21, actor_id=2a7f7b226397f61f42c28bb001000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f1a35c57130>)
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/utils/actor_manager.py", line 192, in apply
    raise e
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/utils/actor_manager.py", line 181, in apply
    return func(self, *args, **kwargs)
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/algorithms/impala/impala.py", line 1110, in <lambda>
    lambda worker: worker.sample()
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 678, in sample
    batches = [self.input_reader.next()]
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/evaluation/sampler.py", line 91, in next
    batches = [self.get_data()]
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/evaluation/sampler.py", line 273, in get_data
    item = next(self._env_runner)
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 348, in run
    outputs = self.step()
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/evaluation/env_runner_v2.py", line 367, in step
    ) = self._base_env.poll()
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/env/multi_agent_env.py", line 634, in poll
    ) = env_state.poll()
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/env/multi_agent_env.py", line 837, in poll
    self.reset()
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/env/multi_agent_env.py", line 921, in reset
    raise e
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/ray/rllib/env/multi_agent_env.py", line 915, in reset
    obs_and_infos = self.env.reset(seed=seed, options=options)
  File "/home/yoshi/super-smash-bros-melee-reinforcement-learning/train/test_template_multispace.py", line 195, in reset
    if self._start_and_connect_server():
  File "/home/yoshi/super-smash-bros-melee-reinforcement-learning/train/test_template_multispace.py", line 238, in _start_and_connect_server
    self.console.run(iso_path=self.iso_path)
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/site-packages/melee/console.py", line 299, in run
    self._process = subprocess.Popen(command, env=env)
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/yoshi/.conda/envs/ssrl/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/map/.local/share/melee-env/Slippi/squashfs-root/usr/bin//dolphin-emu'
